name: CI
on:
  push:
    branches:
      - heroku

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      #- run: flutter test

  build_web:
    name: Build Flutter (Web)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web --web-renderer canvaskit --release

      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./DockerFile
          tags: anchkorg/web-app:latest

  deploy_heroku:
    name: Deploy Heroku
    needs: [build_web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: ${{vars.HEROKU_APP_NAME}}
          heroku_email: ${{vars.HEROKU_EMAIL}}
          justlogin: true
      - name: "Login to heroku registry"
        run: heroku container:login
      - name: "Set heroku stack:set container"
        run: heroku stack:set container --app ${{vars.HEROKU_APP_NAME}}
      - name: "Docker tag to registry.heroku.com"
        run: |
          docker image pull anchkorg/web-app:latest
          docker image
          docker tag anchkorg/web-app:latest registry.heroku.com/${{vars.HEROKU_APP_NAME}}/web
      - name: "Push to heroku registry"
        run: docker push registry.heroku.com/${{vars.HEROKU_APP_NAME}}/web
#            heroku container:push web --app ${{vars.HEROKU_APP_NAME}}  
      - name: "Releases the container"
        run: heroku container:release web --app ${{vars.HEROKU_APP_NAME}} 